apiVersion: apps/v1
kind: Deployment
metadata:
  name: kayaka-re
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kayaka-re
  template:
    metadata:
      labels:
        app: kayaka-re
    spec:
      containers:
        - name: kayaka-re
          image: naveensasalu/kayaka-re:5cbae248a84effbf203b9464afb8b9a1524d6e1a
          ports:
            - containerPort: 80
