apiVersion: apps/v1
kind: Deployment
metadata:
  name: kayaka-re
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kayaka-re
  template:
    metadata:
      labels:
        app: kayaka-re
    spec:
      containers:
        - name: kayaka-re
          image: naveensasalu/kayaka-re:186962b5dbc8bdbfd521087b9f8ac858643d9c07
          ports:
            - containerPort: 80
