apiVersion: apps/v1
kind: Deployment
metadata:
  name: kayaka-re
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kayaka-re
  template:
    metadata:
      labels:
        app: kayaka-re
    spec:
      containers:
        - name: kayaka-re
          image: naveensasalu/kayaka-re:7327e35671cb81861d35532cafb47cdf719f484d
          ports:
            - containerPort: 80
