apiVersion: apps/v1
kind: Deployment
metadata:
  name: kayaka-re
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kayaka-re
  template:
    metadata:
      labels:
        app: kayaka-re
    spec:
      containers:
        - name: kayaka-re
          image: naveensasalu/kayaka-re:590e0e522276d04a3f34dcc01757e3f3b3ed9a53
          ports:
            - containerPort: 80
