apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kayaka-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # This rewrites ALL subpaths of /kayaka-re to index.html
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts: [ "<YOUR_DOMAIN>" ]
      secretName: web-tls
  rules:
    - host: <YOUR_DOMAIN>
      http:
        paths:


spec:
  tls:
   - hosts: re.kaayaka.in
     secretName: web-tls

  rules:
    - host: re.kaayaka.in
      http: 
        paths:
          # (1) Match /kayaka-re
          # (2) Match /kayaka-re/
          # (3) Match /kayaka-re/<anything>   â†’ React SPA routing
          - path: /kayaka-re(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: kayaka-service
                port:
                  number: 80
