apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kayaka-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    #    - host: kayaka.example.com # Change to your domain
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: kayaka-service
              port:
                number: 80
